# Uncomment the next line to define a global platform for your project
platform :ios, '13.0'

target 'Flash Chat iOS13' do
  use_frameworks!
  # Pods for Flash Chat iOS13
  #______________________________________________
  pod 'CLTypingLabel', '~> 0.4.0'
  #______________________________________________
  # Add the Firebase pod for Google Analytics
  # pod 'Firebase/Analytics'

  # Add the pods for any other Firebase products you want to use in your app
  # For example, to use Firebase Authentication and Cloud Firestore
  pod 'Firebase/Auth'
  pod 'Firebase/Firestore'
  #______________________________________________
end
